name: CI_PLAY_STORE_DEPLOY_ANDROID

on:
  push:
    branches: [main]

jobs:
  deployAndroid:
    name: Build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
        id: java

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true
        id: flutter

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: app-release
        with:
          releaseDirectory: ${{ github.workspace }}/build
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '34.0.0'

      - name: Upload Android Tests Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          packageName: dev.bernardoamaral.budgetPlanner
          track: qa
          status: completed
          releaseFiles: ${{ github.workspace }}/build/app-release.aab
          serviceAccountJsonPlainText: '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY_JSON }}'
