name: CI_PLAY_STORE_DEPLOY_ANDROID

on:
  push:
    branches: [main]

jobs:
  deployAndroid:
    name: Build & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
        id: java

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true
        id: flutter

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      - name: Retrieve base64 keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > "${{ github.workspace }}/android-keystore.jks"

      - name: Create key.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/android/app/key.properties
        run: |
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyAlias={{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'storeFile=${{ github.workspace }}/android-keystore.jks' >> $KEYSTORE_PROPERTIES_PATH

      - name: test
        run: cat ${{ github.workspace }}/android/app/key.properties

      - name: Build appBundle
        run: flutter build appbundle --release --no-tree-shake-icons

      - name: Upload Android Tests Release to Play Store
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          packageName: dev.bernardoamaral.budgetPlanner
          track: qa
          status: completed
          releaseFiles: ${{ github.workspace }}/build/app/outputs/bundle/devRelease/app-release.aab
          serviceAccountJsonPlainText: '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY_JSON }}'
